import type { SystemData } from "@/data/systems";
import type { AnalysisMetadata } from "@/context/SystemsContext";
import type { HazardContext } from "@/utils/plrCalculation";
import { determinePLr, plrToCategory } from "@/utils/plrCalculation";
import { CCF_CHECKLIST_TEMPLATE } from "@/data/systems";

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// Map PLr letter to SISTEMA numeric value
function plrToSistemaValue(plr: string): number {
  const map: Record<string, number> = { a: 1, b: 2, c: 3, d: 4, e: 5 };
  return map[plr.toLowerCase()] ?? 0;
}

// Map MTTFd level to SISTEMA enum
function mttfdToSistema(level?: string): string {
  if (level === "low") return "Low";
  if (level === "medium") return "Medium";
  if (level === "high") return "High";
  return "NotSpecified";
}

// Map DC level to SISTEMA enum
function dcToSistema(level?: string): string {
  if (level === "none") return "None";
  if (level === "low") return "Low";
  if (level === "medium") return "Medium";
  if (level === "high") return "High";
  return "NotSpecified";
}

/**
 * Export project data in SISTEMA-compatible XML format.
 * Based on SISTEMA Project XML Schema v2.x structure.
 * Ref: IFA SISTEMA software documentation.
 */
export function exportSistemaXML(
  systems: SystemData[],
  metadata: AnalysisMetadata,
  getHazardContext: (systemId: string) => HazardContext
): string {
  const timestamp = new Date().toISOString();

  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<!-- SISTEMA-compatible XML Export -->\n`;
  xml += `<!-- Generated by Tunnel Vehicle System (TVS) Safety Analysis Platform -->\n`;
  xml += `<!-- Export date: ${timestamp} -->\n`;
  xml += `<!-- Standard: ISO 13849-1:2023 -->\n`;
  xml += `<SistemaProject version="2.0" xmlns="http://www.dguv.de/ifa/sistema">\n`;
  xml += `  <ProjectInfo>\n`;
  xml += `    <Name>${escapeXml("TVS Safety Analysis")}</Name>\n`;
  xml += `    <Description>${escapeXml("Tunnel Vehicle System — Functional Safety Analysis per ISO 13849-1")}</Description>\n`;
  xml += `    <Engineer>${escapeXml(metadata.engineerName)}</Engineer>\n`;
  xml += `    <Date>${escapeXml(metadata.date)}</Date>\n`;
  xml += `    <LastModified>${escapeXml(metadata.lastModified)}</LastModified>\n`;
  xml += `    <Standard>ISO 13849-1:2023</Standard>\n`;
  xml += `    <Notes>${escapeXml(metadata.notes)}</Notes>\n`;
  xml += `  </ProjectInfo>\n\n`;

  for (const system of systems) {
    const ctx = getHazardContext(system.id);
    const plr = determinePLr(ctx.severity, ctx.frequency, ctx.avoidance);
    const cat = plrToCategory(plr);

    xml += `  <Subsystem id="${escapeXml(system.id)}">\n`;
    xml += `    <Name>${escapeXml(system.name)}</Name>\n`;
    xml += `    <NameFr>${escapeXml(system.nameFr)}</NameFr>\n`;
    xml += `    <Description>${escapeXml(system.description)}</Description>\n`;
    xml += `    <TopEvent>${escapeXml(system.topEvent)}</TopEvent>\n\n`;

    // Hazard context & PLr
    xml += `    <HazardAnalysis>\n`;
    xml += `      <Severity>${escapeXml(ctx.severity)}</Severity>\n`;
    xml += `      <SeverityJustification>${escapeXml(ctx.severityJustification)}</SeverityJustification>\n`;
    xml += `      <Frequency>${escapeXml(ctx.frequency)}</Frequency>\n`;
    xml += `      <FrequencyJustification>${escapeXml(ctx.frequencyJustification)}</FrequencyJustification>\n`;
    xml += `      <Avoidance>${escapeXml(ctx.avoidance)}</Avoidance>\n`;
    xml += `      <AvoidanceJustification>${escapeXml(ctx.avoidanceJustification)}</AvoidanceJustification>\n`;
    xml += `      <RequiredPL value="${plrToSistemaValue(plr)}">${plr.toUpperCase()}</RequiredPL>\n`;
    xml += `      <MinCategory>${escapeXml(cat)}</MinCategory>\n`;
    xml += `    </HazardAnalysis>\n\n`;

    // Safety functions
    xml += `    <SafetyFunctions>\n`;
    for (const sf of system.safetyFunctions) {
      xml += `      <SafetyFunction id="${escapeXml(sf.id)}">\n`;
      xml += `        <Name>${escapeXml(sf.function)}</Name>\n`;
      xml += `        <Description>${escapeXml(sf.description)}</Description>\n`;
      xml += `        <RequiredPL>${escapeXml(sf.plr.toUpperCase())}</RequiredPL>\n`;
      xml += `        <Category>${escapeXml(sf.category)}</Category>\n`;
      
      // Hardware metrics
      xml += `        <HardwareMetrics>\n`;
      xml += `          <MTTFd years="${sf.mttfd ?? ""}" level="${mttfdToSistema(sf.mttfdLevel)}" />\n`;
      xml += `          <DCavg percent="${sf.dcavg ?? ""}" level="${dcToSistema(sf.dcLevel)}" />\n`;
      xml += `        </HardwareMetrics>\n`;
      
      // CCF
      if (sf.ccfChecklist && sf.ccfChecklist.length > 0) {
        xml += `        <CCFAnalysis score="${sf.ccfScore ?? 0}" pass="${(sf.ccfScore ?? 0) >= 65}">\n`;
        for (const item of sf.ccfChecklist) {
          xml += `          <Measure id="${escapeXml(item.id)}" applied="${item.applied}" score="${item.score}">${escapeXml(item.measure)}</Measure>\n`;
        }
        xml += `        </CCFAnalysis>\n`;
      }
      
      xml += `      </SafetyFunction>\n`;
    }
    xml += `    </SafetyFunctions>\n\n`;

    // FMEA
    xml += `    <FMEA>\n`;
    for (const row of system.fmea) {
      xml += `      <Row id="${escapeXml(row.id)}">\n`;
      xml += `        <Component>${escapeXml(row.component)}</Component>\n`;
      xml += `        <FailureMode>${escapeXml(row.failureMode)}</FailureMode>\n`;
      xml += `        <Cause>${escapeXml(row.cause)}</Cause>\n`;
      xml += `        <Effect>${escapeXml(row.effect)}</Effect>\n`;
      xml += `        <InitialAssessment severity="${row.severity}" occurrence="${row.occurrence}" detection="${row.detection}" rpn="${row.rpn}" />\n`;
      if (row.residualRpn !== undefined) {
        xml += `        <ResidualAssessment severity="${row.residualSeverity ?? ""}" occurrence="${row.residualOccurrence ?? ""}" detection="${row.residualDetection ?? ""}" rpn="${row.residualRpn}" accepted="${row.riskAccepted ?? false}" />\n`;
      }
      xml += `        <Mitigation>${escapeXml(row.mitigation)}</Mitigation>\n`;
      xml += `      </Row>\n`;
    }
    xml += `    </FMEA>\n\n`;

    // Risks
    xml += `    <RiskAssessment>\n`;
    for (const risk of system.risks) {
      xml += `      <Risk id="${escapeXml(risk.id)}" severity="${risk.severity}" probability="${risk.probability}" level="${escapeXml(risk.riskLevel)}">\n`;
      xml += `        <Hazard>${escapeXml(risk.hazard)}</Hazard>\n`;
      xml += `      </Risk>\n`;
    }
    xml += `    </RiskAssessment>\n\n`;

    // Consequences & Safety Measures
    xml += `    <Consequences>\n`;
    for (const c of system.consequences) {
      xml += `      <Item>${escapeXml(c)}</Item>\n`;
    }
    xml += `    </Consequences>\n`;
    xml += `    <SafetyMeasures>\n`;
    for (const m of system.safetyMeasures) {
      xml += `      <Item>${escapeXml(m)}</Item>\n`;
    }
    xml += `    </SafetyMeasures>\n`;

    xml += `  </Subsystem>\n\n`;
  }

  xml += `</SistemaProject>\n`;
  return xml;
}

export function downloadSistemaXML(
  systems: SystemData[],
  metadata: AnalysisMetadata,
  getHazardContext: (systemId: string) => HazardContext
) {
  const xml = exportSistemaXML(systems, metadata, getHazardContext);
  const blob = new Blob([xml], { type: "application/xml;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `TVS_Safety_Analysis_SISTEMA_${new Date().toISOString().split("T")[0]}.xml`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
